/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.transversal.vista;

import javax.swing.JOptionPane;
import proyecto.transversal.accesoADatos.MateriaData;
import proyecto.transversal.entidades.Materia;

/**
 *
 * @author Usuario
 */
public class Vista_Materia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Materia
     */
    public Vista_Materia() {
        initComponents();
        jbNuevo.setEnabled(false);
        jbEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTituloMateria = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlAnio = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfAnio = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setToolTipText("");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloMateria.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlTituloMateria.setText("MATERIA");
        getContentPane().add(jlTituloMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 6, 84, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 46, 420, -1));

        jlCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCodigo.setText("Codigo:");
        getContentPane().add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 99, -1, -1));

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlNombre.setText("Nombre:");
        getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 185, -1, -1));

        jlAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAnio.setText("Año:");
        getContentPane().add(jlAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 267, -1, -1));

        jlEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlEstado.setText("Estado:");
        getContentPane().add(jlEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 342, -1, -1));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 90, -1, -1));
        getContentPane().add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 94, 113, -1));
        getContentPane().add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 180, 338, -1));
        getContentPane().add(jtfAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 262, 113, -1));
        getContentPane().add(jrbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 329, -1, -1));

        jbNuevo.setText("Nuevo");
        jbNuevo.setMaximumSize(new java.awt.Dimension(79, 25));
        jbNuevo.setMinimumSize(new java.awt.Dimension(79, 25));
        getContentPane().add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 480, -1, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 480, -1, -1));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 480, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.setMaximumSize(new java.awt.Dimension(79, 25));
        jbSalir.setMinimumSize(new java.awt.Dimension(79, 25));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 480, 67, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    MateriaData md = new MateriaData();
//    private boolean modificar=false;
    private int id;
    private String nombre = null;
    private int anioMat;
    boolean activo = false;

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        try {
            id = Integer.parseInt(jtfCodigo.getText());
            Materia mate = md.buscarMateria(id);
            nombre = mate.getNombre();
            anioMat = mate.getAnioMateria();
            activo = mate.isActivo();

            jtfNombre.setText(nombre);
            jtfAnio.setText(anioMat + "");
            jrbEstado.setSelected(activo);

//            modificar=true;
        } catch (NullPointerException ex) {
            // no la manejo aqui, ya que el mismo metodo de "buscarMateria(int id)" en MateriaData me tira el mensaje...
//            JOptionPane.showMessageDialog(this, "");
            jtfNombre.setText(null);
            jtfAnio.setText(null);
            jrbEstado.setSelected(false);
            activo = false;
//            jbEliminar.setEnabled(false);

//            modificar=false;   
        } catch (NumberFormatException ex) {
            // en caso de que el usuario deje el ID vacio
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero para la consulta");
            jtfNombre.setText(null);
            jtfAnio.setText(null);
            jrbEstado.setSelected(false);
            activo = false;
//            jbEliminar.setEnabled(false);
        }
        if (activo == true) {
            jbEliminar.setEnabled(true);
        } else {
            jbEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // PARA GUARDAR MATERIA
        try {
            id = Integer.parseInt(jtfCodigo.getText());
        } catch (NullPointerException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "PROBANDO A VER SI PASA");
            boolean decision = false;
        }
        boolean decision = false;
        try {
            if (md.buscarMateria(id).getIdMateria() == id) {
                decision = true;
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Se agragara como materia nueva");
            decision = false;
        }
        if (decision == true) {
            //ME EDITA LA MATERIA CORRECTAMENTE

            System.out.println("entra a la parte de editar");
            JOptionPane.showMessageDialog(null, "Entra a Editar (1)");
            try {
                nombre = jtfNombre.getText();
                anioMat = Integer.parseInt(jtfAnio.getText());
                activo = jrbEstado.isSelected();
                System.out.println(id + "-" + nombre + "-" + anioMat + "-" + activo);
                Materia mat = new Materia(id, nombre, anioMat, activo);
                md.modificarMateria(mat);

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "Debe agregar solo números en año");
                jtfAnio.setText(null);

            } catch (NullPointerException ex) {

                JOptionPane.showMessageDialog(null, "No debe haber campos vacios");
            }

        } else if (decision == false) {

            //System.out.println("entro a guardar Materia");
            //JOptionPane.showMessageDialog(null, "Entra a GUARDAR (2)");
            nombre = jtfNombre.getText();
            anioMat = Integer.parseInt(jtfAnio.getText());
//            System.out.println(""+jrbEstado.isSelected());
            activo = jrbEstado.isSelected();
            MateriaData mD = new MateriaData();
            String nombreMateria = null;
            boolean re = false;
            for (Materia bus : mD.listarMaterias()) {
                nombreMateria = bus.getNombre();
                if (nombreMateria.equalsIgnoreCase(nombre)) {
                    JOptionPane.showMessageDialog(null, "Materia repetida");
                    re = true;
                }
            }
            if (re == false) {
                Materia mat = new Materia(nombre, anioMat, activo);
                md.guardarMateria(mat);
            }
//            System.out.println(""+nombre+"-"+anioMat+"-"+activo);

        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
//        try{
        id = Integer.parseInt(jtfCodigo.getText());
        activo = jrbEstado.isSelected();
        if (activo == true) {
            md.eliminarMateria(id);
            jrbEstado.isSelected();
        } else {

        }

//        }catch (NullPointerException ex){
//        JOptionPane.showMessageDialog(null, "Debe Seleccionar una materia para eliminar");
//        }
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlAnio;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTituloMateria;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtfAnio;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
